<?php

namespace AppBundle\Repository;

/**
 * depenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class depenseRepository extends \Doctrine\ORM\EntityRepository
{
}
